description: >
  The AsyncAPI Generator Docker executor.
docker:
  - image: 'asyncapi/generator:<< parameters.tag >>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific asyncapi/generator image variant:
      https://hub.docker.com/r/asyncapi/generator/tags
    type: string
